name: Test eyes on all platforms
on:
  push:
  pull_request:
jobs:
  java-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java-version: [ "17" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - run: pip install -r requirements.txt
      - run: pytest -vv
